### ISSUE TITLE
Failing to do recursive configuration for sam_pre_release branch

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#182] opened 2021-05-27 16:10 UTC

**Comment by terencewtli** [comment] 2021-05-27 21:06
`autoreconf -i` does not produce these two lines (which I believe are needed for `smithlab_cpp`) in the current `sam_pre_release` clone:
```
configure.ac:33: installing './ar-lib'
configure.ac:33: installing './compile'
```
I thought it was because of this line, but it's identical in both `configure.ac` versions in current clone and methpipe-4.1.2:

```AX_SUBDIRS_CONFIGURE([src/smithlab_cpp], [--enable-hts])```

**Comment by guilhermesena1** [comment] 2021-06-16 02:56
I can reproduce this when cloning and using `autoreconf -i`, which gives me the log below. However, if I go to `src/smithlab_cpp` and run `autoreconf -i` there as well, the recursive configuration works fine.

If that is the source of the problem, I think we just need to make clear that, if the repo is cloned and the user wishes to use autotools, it needs to be run in both those directories.

**Comment by guilhermesena1** [comment] 2021-06-30 20:44
I think 983481a fixes this?

**Comment by terencewtli** [comment] 2021-07-26 21:27
Closing this because the `sam_pre_release` branch no longer exists.

**Closed by terencewtli** 2021-07-26 21:27 UTC
